# -*- coding: utf-8 -*-
"""Untitled0.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1YMjbSY78EAVoi0gLtRPPO3pPeDISyl9r
"""

!pip install -q kaggle

import os

os.environ["KAGGLE_USERNAME"] =
os.environ["KAGGLE_KEY"] =

# Test access to the SemanticKITTI dataset
!kaggle datasets files hbenallal/semantickitti

import os

os.makedirs("/content/semantic_kitti_sample", exist_ok=True)

for i in range(10):
    filename = f"dataset/sequences/00/velodyne/{i:06d}.bin"

    !kaggle datasets download \
        -d hbenallal/semantickitti \
        -f "$filename" \
        -p /content/semantic_kitti_sample \
        --unzip

import glob
import os
import numpy as np

files = sorted(
    glob.glob("/content/semantic_kitti_sample/*.bin")
)

print("Frames found:", len(files))

for path in files:
    points = np.fromfile(path, dtype=np.float32).reshape(-1, 4)

    xyz = points[:, :3]
    intensity = points[:, 3]

    horizontal_range = np.sqrt(xyz[:, 0]**2 + xyz[:, 1]**2)

    print(
        f"{os.path.basename(path)} | "
        f"points={len(points):6d} | "
        f"range={horizontal_range.min():5.2f}-{horizontal_range.max():5.2f} m | "
        f"Z={xyz[:,2].min():6.2f}-{xyz[:,2].max():5.2f} m | "
        f"intensity={intensity.min():.2f}-{intensity.max():.2f} | "
        f"NaN={np.isnan(points).sum()} | "
        f"Inf={np.isinf(points).sum()}"
    )

import numpy as np
from collections import defaultdict, Counter
import time
import os

# ─────────────────────────────────────────
# CONFIG
# ─────────────────────────────────────────
BANDS = [
    (0,  10,  0.05, 0),
    (10, 30,  0.15, 1),
    (30, 100, 0.50, 2),
]

FILES = [
    f"/content/semantic_kitti_sample/{i:06d}.bin"
    for i in range(10)
]

# ─────────────────────────────────────────
# CORE FUNCTIONS
# ─────────────────────────────────────────

def load_points(path):
    return np.fromfile(path, dtype=np.float32).reshape(-1, 4)

def assign_levels(points):
    dist     = np.sqrt(points[:,0]**2 + points[:,1]**2)
    levels   = np.zeros(len(points), dtype=np.int32)
    vox_size = np.zeros(len(points), dtype=np.float32)
    for d_min, d_max, size, level in BANDS:
        mask = (dist >= d_min) & (dist < d_max)
        levels[mask]   = level
        vox_size[mask] = size
    return levels, vox_size, dist

def build_hash_grid(points, levels, vox_size):
    coords = np.floor(
        points[:,:3] / vox_size[:,None]
    ).astype(np.int32)

    hash_grid = defaultdict(lambda: {
        "point_indices": [],
        "level": None,
        "vox_size": None
    })

    for i in range(len(points)):
        key = (
            int(levels[i]),
            int(coords[i,0]),
            int(coords[i,1]),
            int(coords[i,2])
        )
        hash_grid[key]["point_indices"].append(i)
        hash_grid[key]["level"]    = int(levels[i])
        hash_grid[key]["vox_size"] = float(vox_size[i])

    return hash_grid

def compute_voxel_features(hash_grid, points):
    features = {}
    for key, data in hash_grid.items():
        idx = data["point_indices"]
        pts = points[idx]
        z   = pts[:,2]
        features[key] = {
            "point_count":    len(idx),
            "height_mean":    float(z.mean()),
            "height_min":     float(z.min()),
            "height_max":     float(z.max()),
            "height_var":     float(z.var()),
            "height_range":   float(z.max() - z.min()),
            "intensity_mean": float(pts[:,3].mean()),
            "level":          data["level"],
            "vox_size":       data["vox_size"],
        }
    return features

def compute_voxel_centers(hash_grid):
    centers = {}
    for key, data in hash_grid.items():
        _, ix, iy, iz = key
        vs = data["vox_size"]
        centers[key] = (
            (ix + 0.5) * vs,
            (iy + 0.5) * vs,
            (iz + 0.5) * vs,
        )
    return centers

def uniform_voxel_count(points, size=0.05):
    coords = np.floor(points[:,:3] / size).astype(np.int32)
    return len(set(map(tuple, coords.tolist())))

def correctness_checks(hash_grid, features):
    errors = []

    # Check 1 — no duplicate keys
    all_keys = list(hash_grid.keys())
    if len(all_keys) != len(set(all_keys)):
        errors.append("KEY COLLISION detected")

    # Check 2 — no empty voxels
    empty = [k for k,v in hash_grid.items()
             if len(v["point_indices"]) == 0]
    if empty:
        errors.append(f"{len(empty)} empty voxels found")

    # Check 3 — voxel size matches level
    size_map = {0: 0.05, 1: 0.15, 2: 0.50}
    mismatches = [
        k for k, v in features.items()
        if abs(v["vox_size"] - size_map[k[0]]) > 1e-6
    ]
    if mismatches:
        errors.append(f"{len(mismatches)} voxel size mismatches")

    # Check 4 — point count > 0
    zero_pts = [k for k,v in features.items()
                if v["point_count"] == 0]
    if zero_pts:
        errors.append(f"{len(zero_pts)} voxels with zero points")

    return errors

# ─────────────────────────────────────────
# MAIN LOOP
# ─────────────────────────────────────────

print(f"{'Frame':<12} {'Points':>8} {'Uniform':>10} "
      f"{'Adaptive':>10} {'Reduction':>10} "
      f"{'L0':>8} {'L1':>8} {'L2':>8} "
      f"{'Time(ms)':>10} {'Checks'}")
print("-" * 100)

all_results = []

for fpath in FILES:
    fname = os.path.basename(fpath)
    t0    = time.time()

    # Pipeline
    points              = load_points(fpath)
    levels, vox_size, dist = assign_levels(points)
    hash_grid           = build_hash_grid(points, levels, vox_size)
    features            = compute_voxel_features(hash_grid, points)
    centers             = compute_voxel_centers(hash_grid)

    elapsed_ms = (time.time() - t0) * 1000

    # Counts
    uniform_v  = uniform_voxel_count(points)
    adaptive_v = len(hash_grid)
    reduction  = uniform_v / adaptive_v

    level_counts = Counter(k[0] for k in hash_grid.keys())

    # Correctness
    errors      = correctness_checks(hash_grid, features)
    check_str   = "✓ PASS" if not errors else f"✗ {errors[0]}"

    result = {
        "frame":      fname,
        "points":     len(points),
        "uniform":    uniform_v,
        "adaptive":   adaptive_v,
        "reduction":  reduction,
        "l0":         level_counts[0],
        "l1":         level_counts[1],
        "l2":         level_counts[2],
        "time_ms":    elapsed_ms,
        "errors":     errors,
    }
    all_results.append(result)

    print(f"{fname:<12} {len(points):>8,} {uniform_v:>10,} "
          f"{adaptive_v:>10,} {reduction:>9.2f}x "
          f"{level_counts[0]:>8,} {level_counts[1]:>8,} "
          f"{level_counts[2]:>8,} {elapsed_ms:>9.1f}ms  {check_str}")

# ─────────────────────────────────────────
# SUMMARY
# ─────────────────────────────────────────

print("\n" + "=" * 100)
print("SUMMARY ACROSS 10 FRAMES")
print("=" * 100)

avg_points   = np.mean([r["points"]   for r in all_results])
avg_uniform  = np.mean([r["uniform"]  for r in all_results])
avg_adaptive = np.mean([r["adaptive"] for r in all_results])
avg_red      = np.mean([r["reduction"]for r in all_results])
avg_time     = np.mean([r["time_ms"]  for r in all_results])
avg_l0       = np.mean([r["l0"]       for r in all_results])
avg_l1       = np.mean([r["l1"]       for r in all_results])
avg_l2       = np.mean([r["l2"]       for r in all_results])

print(f"  Avg points per frame : {avg_points:,.0f}")
print(f"  Avg uniform voxels   : {avg_uniform:,.0f}")
print(f"  Avg adaptive voxels  : {avg_adaptive:,.0f}")
print(f"  Avg reduction        : {avg_red:.2f}x")
print(f"  Avg time per frame   : {avg_time:.1f} ms")
print(f"  Avg L0 voxels (5cm)  : {avg_l0:,.0f}")
print(f"  Avg L1 voxels (15cm) : {avg_l1:,.0f}")
print(f"  Avg L2 voxels (50cm) : {avg_l2:,.0f}")

all_errors = [e for r in all_results for e in r["errors"]]
if not all_errors:
    print("\n  ✓ All correctness checks passed across all 10 frames")
else:
    print(f"\n  ✗ Errors found: {set(all_errors)}")

print("\nLEVEL BREAKDOWN (averages)")
print(f"  L0 (5cm,  0-10m)  : {avg_l0:,.0f} voxels  "
      f"({avg_l0/avg_adaptive*100:.1f}% of adaptive)")
print(f"  L1 (15cm, 10-30m) : {avg_l1:,.0f} voxels  "
      f"({avg_l1/avg_adaptive*100:.1f}% of adaptive)")
print(f"  L2 (50cm, 30-100m): {avg_l2:,.0f} voxels  "
      f"({avg_l2/avg_adaptive*100:.1f}% of adaptive)")

import numpy as np
import matplotlib.pyplot as plt
import os
import json
import time
from collections import Counter

# ─────────────────────────────────────────
# CONFIG
# ─────────────────────────────────────────
BANDS = [
    (0,  10,  0.05, 0),
    (10, 30,  0.15, 1),
    (30, 100, 0.50, 2),
]

SIZE_MAP = np.array([0.05, 0.15, 0.50], dtype=np.float32)

FILES = [
    f"/content/semantic_kitti_sample/{i:06d}.bin"
    for i in range(10)
]

SAVE_DIR = "/kaggle/working/voxel_store"
os.makedirs(SAVE_DIR, exist_ok=True)

# ─────────────────────────────────────────
# PIPELINE
# ─────────────────────────────────────────
def load_points(path):
    return np.fromfile(path, dtype=np.float32).reshape(-1, 4)


class VoxelPipeline:
    def __init__(self, max_points=150000, max_voxels=100000):
        self.max_points = max_points
        self.max_voxels = max_voxels
        self.levels   = np.zeros(max_points, dtype=np.int32)
        self.vox_size = np.zeros(max_points, dtype=np.float32)
        self.dist     = np.zeros(max_points, dtype=np.float32)
        self.count    = np.zeros(max_voxels, dtype=np.int32)
        self.z_sum    = np.zeros(max_voxels, dtype=np.float64)
        self.z_sum2   = np.zeros(max_voxels, dtype=np.float64)
        self.z_min    = np.zeros(max_voxels, dtype=np.float64)
        self.z_max    = np.zeros(max_voxels, dtype=np.float64)
        self.i_sum    = np.zeros(max_voxels, dtype=np.float64)

    def process(self, points):
        N = len(points)

        # ── assign levels ──────────────────────────────
        dist     = self.dist[:N]
        levels   = self.levels[:N]
        vox_size = self.vox_size[:N]

        np.sqrt(points[:,0]**2 + points[:,1]**2, out=dist)

        levels[:]   = 2;  vox_size[:] = 0.50
        m1 = dist < 30;   levels[m1]  = 1; vox_size[m1] = 0.15
        m0 = dist < 10;   levels[m0]  = 0; vox_size[m0] = 0.05

        # ── hash grid ──────────────────────────────────
        coords = np.floor(
            points[:,:3] / vox_size[:,None]
        ).astype(np.int32)

        keys   = np.stack([levels,
                           coords[:,0],
                           coords[:,1],
                           coords[:,2]], axis=1).astype(np.int32)
        keys_c = np.ascontiguousarray(keys)
        keys_v = keys_c.view(
            np.dtype((np.void, keys_c.dtype.itemsize * 4))
        ).ravel()

        unique_void, inverse = np.unique(keys_v, return_inverse=True)
        unique_keys = unique_void.view(np.int32).reshape(-1, 4)

        sort_order     = np.argsort(inverse, kind='stable')
        sorted_inverse = inverse[sort_order]
        split_points   = np.searchsorted(
            sorted_inverse, np.arange(len(unique_keys))
        )

        # ── features ───────────────────────────────────
        V     = len(unique_keys)
        z     = points[:,2].astype(np.float64)
        inten = points[:,3].astype(np.float64)

        count  = self.count[:V];  count[:]  = 0
        z_sum  = self.z_sum[:V];  z_sum[:]  = 0
        z_sum2 = self.z_sum2[:V]; z_sum2[:] = 0
        z_min  = self.z_min[:V];  z_min[:]  =  np.inf
        z_max  = self.z_max[:V];  z_max[:]  = -np.inf
        i_sum  = self.i_sum[:V];  i_sum[:]  = 0

        np.add.at(count,  inverse, 1)
        np.add.at(z_sum,  inverse, z)
        np.add.at(z_sum2, inverse, z**2)
        np.minimum.at(z_min, inverse, z)
        np.maximum.at(z_max, inverse, z)
        np.add.at(i_sum,  inverse, inten)

        z_mean  = z_sum  / count
        z_var   = z_sum2 / count - z_mean**2
        z_range = z_max  - z_min
        i_mean  = i_sum  / count

        lv = unique_keys[:,0]
        vs = SIZE_MAP[lv]
        cx = (unique_keys[:,1] + 0.5) * vs
        cy = (unique_keys[:,2] + 0.5) * vs
        cz = (unique_keys[:,3] + 0.5) * vs

        return {
            "unique_keys":    unique_keys,
            "levels":         lv,
            "vox_size":       vs,
            "center_x":       cx,
            "center_y":       cy,
            "center_z":       cz,
            "point_count":    count.copy(),
            "height_mean":    z_mean.copy(),
            "height_min":     z_min.copy(),
            "height_max":     z_max.copy(),
            "height_var":     z_var.copy(),
            "height_range":   z_range.copy(),
            "intensity_mean": i_mean.copy(),
        }


# ─────────────────────────────────────────
# STORAGE
# ─────────────────────────────────────────
def save_voxels(features, frame_name, save_dir):
    """
    Save all voxel arrays as a single compressed .npz file.
    One file per frame. Loads back instantly with np.load.

    Stored arrays:
      keys        — (V,4) int32  [level, ix, iy, iz]
      levels      — (V,)  int32
      vox_size    — (V,)  float32
      center_xyz  — (V,3) float32  [cx, cy, cz]
      point_count — (V,)  int32
      height_mean — (V,)  float32
      height_min  — (V,)  float32
      height_max  — (V,)  float32
      height_var  — (V,)  float32
      height_range— (V,)  float32
      intensity   — (V,)  float32
    """
    frame_id = os.path.splitext(frame_name)[0]
    out_path = os.path.join(save_dir, f"{frame_id}_voxels.npz")

    center_xyz = np.stack([
        features["center_x"],
        features["center_y"],
        features["center_z"]
    ], axis=1).astype(np.float32)

    np.savez_compressed(
        out_path,
        keys         = features["unique_keys"].astype(np.int32),
        levels       = features["levels"].astype(np.int32),
        vox_size     = features["vox_size"].astype(np.float32),
        center_xyz   = center_xyz,
        point_count  = features["point_count"].astype(np.int32),
        height_mean  = features["height_mean"].astype(np.float32),
        height_min   = features["height_min"].astype(np.float32),
        height_max   = features["height_max"].astype(np.float32),
        height_var   = features["height_var"].astype(np.float32),
        height_range = features["height_range"].astype(np.float32),
        intensity    = features["intensity_mean"].astype(np.float32),
    )
    return out_path


def load_voxels(frame_id, save_dir):
    """
    Load a saved voxel frame back into a features dict.
    Usage: features = load_voxels("000000", SAVE_DIR)
    """
    path = os.path.join(save_dir, f"{frame_id}_voxels.npz")
    d    = np.load(path)
    return {
        "unique_keys":    d["keys"],
        "levels":         d["levels"],
        "vox_size":       d["vox_size"],
        "center_x":       d["center_xyz"][:,0],
        "center_y":       d["center_xyz"][:,1],
        "center_z":       d["center_xyz"][:,2],
        "point_count":    d["point_count"],
        "height_mean":    d["height_mean"],
        "height_min":     d["height_min"],
        "height_max":     d["height_max"],
        "height_var":     d["height_var"],
        "height_range":   d["height_range"],
        "intensity_mean": d["intensity"],
    }


def save_metadata(results, save_dir):
    """
    Save per-frame summary stats as JSON.
    Useful for the benchmark table later.
    """
    meta_path = os.path.join(save_dir, "metadata.json")
    with open(meta_path, "w") as f:
        json.dump(results, f, indent=2)
    return meta_path


# ─────────────────────────────────────────
# QUALITY REPORT
# ─────────────────────────────────────────
def voxel_quality_report(features, points):
    pcount = features["point_count"]
    hrange = features["height_range"]
    hvar   = features["height_var"]
    levels = features["levels"]

    print("=" * 60)
    print("VOXEL QUALITY REPORT")
    print("=" * 60)

    # ── overall ────────────────────────────────────────
    print(f"\n── Overall ──")
    print(f"  Total voxels      : {len(pcount):,}")
    print(f"  Total points      : {len(points):,}")
    print(f"  Compression ratio : {len(points)/len(pcount):.2f} pts/voxel")

    # ── points per voxel ───────────────────────────────
    print(f"\n── Points per voxel ──")
    print(f"  Min    : {pcount.min()}")
    print(f"  Max    : {pcount.max()}")
    print(f"  Mean   : {pcount.mean():.2f}")
    print(f"  Median : {np.median(pcount):.1f}")
    print(f"  1-pt voxels  : {(pcount==1).sum():,} "
          f"({(pcount==1).mean()*100:.1f}%)")
    print(f"  >10pt voxels : {(pcount>10).sum():,} "
          f"({(pcount>10).mean()*100:.1f}%)")

    # ── height range ───────────────────────────────────
    print(f"\n── Height range per voxel ──")
    print(f"  Min  : {hrange.min():.4f} m")
    print(f"  Max  : {hrange.max():.4f} m")
    print(f"  Mean : {hrange.mean():.4f} m")
    print(f"  Suspicious (>2m) : {(hrange>2).sum():,}")
    print(f"  Flat (=0m)       : {(hrange==0).sum():,}")

    # ── per level ──────────────────────────────────────
    print(f"\n── Per-level breakdown ──")
    size_labels = {0: "5cm", 1: "15cm", 2: "50cm"}
    for lv in [0, 1, 2]:
        mask = levels == lv
        if mask.sum() == 0:
            continue
        pc = pcount[mask]
        hr = hrange[mask]
        print(f"\n  L{lv} ({size_labels[lv]}) — {mask.sum():,} voxels")
        print(f"    pts/voxel : "
              f"min={pc.min()} "
              f"mean={pc.mean():.2f} "
              f"max={pc.max()}")
        print(f"    height_range : "
              f"min={hr.min():.3f} "
              f"mean={hr.mean():.3f} "
              f"max={hr.max():.3f}")
        print(f"    single-pt : {(pc==1).sum():,} "
              f"({(pc==1).mean()*100:.1f}%)")

    # ── spatial coverage ───────────────────────────────
    print(f"\n── Spatial coverage ──")
    print(f"  X : {features['center_x'].min():.1f} "
          f"to {features['center_x'].max():.1f} m")
    print(f"  Y : {features['center_y'].min():.1f} "
          f"to {features['center_y'].max():.1f} m")
    print(f"  Z : {features['center_z'].min():.1f} "
          f"to {features['center_z'].max():.1f} m")


def check_zone_boundaries(features):
    print(f"\n── Zone boundary check ──")
    cx   = features["center_x"]
    cy   = features["center_y"]
    lv   = features["levels"]
    dist = np.sqrt(cx**2 + cy**2)

    for boundary, lo, hi, lv_a, lv_b in [
        (10, 8,  12, 0, 1),
        (30, 28, 32, 1, 2),
    ]:
        zone = (dist > lo) & (dist < hi)
        if zone.sum() == 0:
            continue
        la = (lv[zone] == lv_a).sum()
        lb = (lv[zone] == lv_b).sum()
        print(f"\n  {lo}–{hi}m (around {boundary}m boundary)")
        print(f"    L{lv_a} voxels : {la}")
        print(f"    L{lv_b} voxels : {lb}")

    # Use tolerance of half a 50cm voxel = 0.25m
    TOLERANCE = 0.25
    l0_far  = ((lv == 0) & (dist > 10 + TOLERANCE)).sum()
    l2_near = ((lv == 2) & (dist < 30 - TOLERANCE)).sum()

    print(f"\n  L0 voxels beyond {10+TOLERANCE}m : {l0_far} "
          f"{'✓' if l0_far==0 else '✗ WARNING'}")
    print(f"  L2 voxels within {30-TOLERANCE}m : {l2_near} "
          f"{'✓' if l2_near==0 else '✗ WARNING'}")
    print(f"  (tolerance = {TOLERANCE}m = half one L2 voxel width)")

# ─────────────────────────────────────────
# QUALITY PLOTS
# ─────────────────────────────────────────
def voxel_quality_plots(features, frame_name, save_dir):
    pcount = features["point_count"]
    hrange = features["height_range"]
    hvar   = features["height_var"]
    levels = features["levels"]
    cx     = features["center_x"]
    cy     = features["center_y"]

    colors = ['steelblue', 'darkorange', 'green']
    labels = ['L0 5cm (0–10m)',
              'L1 15cm (10–30m)',
              'L2 50cm (30–100m)']

    fig, axes = plt.subplots(2, 3, figsize=(16, 9))
    fig.suptitle(f"Voxel Quality — {frame_name}", fontsize=14)

    # ── 1: points per voxel ────────────────────────────
    ax = axes[0, 0]
    for lv in [0, 1, 2]:
        mask = levels == lv
        ax.hist(pcount[mask], bins=50, alpha=0.6,
                color=colors[lv], label=labels[lv])
    ax.set_xlabel("Points per voxel")
    ax.set_ylabel("Voxel count (log)")
    ax.set_title("Points per Voxel")
    ax.legend(fontsize=8)
    ax.set_yscale('log')

    # ── 2: height range ────────────────────────────────
    ax = axes[0, 1]
    for lv in [0, 1, 2]:
        mask = levels == lv
        ax.hist(hrange[mask], bins=50, alpha=0.6,
                color=colors[lv], label=labels[lv])
    ax.set_xlabel("Height range (m)")
    ax.set_title("Height Range Distribution")
    ax.legend(fontsize=8)

    # ── 3: height std dev ──────────────────────────────
    ax = axes[0, 2]
    for lv in [0, 1, 2]:
        mask = levels == lv
        ax.hist(np.sqrt(hvar[mask] + 1e-9),
                bins=50, alpha=0.6,
                color=colors[lv], label=labels[lv])
    ax.set_xlabel("Height std dev (m)")
    ax.set_title("Height Variance Distribution")
    ax.legend(fontsize=8)

    # ── 4: top-down by level ───────────────────────────
    ax = axes[1, 0]
    for lv in [0, 1, 2]:
        mask = levels == lv
        ax.scatter(cx[mask], cy[mask],
                   s=0.3, alpha=0.4,
                   color=colors[lv], label=labels[lv])
    # Draw boundary rings
    for r, c in [(10,'red'), (30,'purple')]:
        circle = plt.Circle((0,0), r, color=c,
                             fill=False, linewidth=1,
                             linestyle='--', alpha=0.7)
        ax.add_patch(circle)
    ax.set_xlabel("X (m)"); ax.set_ylabel("Y (m)")
    ax.set_title("Top-down: Resolution Zones")
    ax.legend(fontsize=7, markerscale=5)
    ax.set_aspect('equal')

    # ── 5: point density ───────────────────────────────
    ax = axes[1, 1]
    sc = ax.scatter(cx, cy,
                    c=np.log1p(pcount),
                    s=0.3, alpha=0.5, cmap='plasma')
    plt.colorbar(sc, ax=ax, label='log(point count)')
    ax.set_xlabel("X (m)"); ax.set_ylabel("Y (m)")
    ax.set_title("Top-down: Point Density")
    ax.set_aspect('equal')

    # ── 6: mean height ─────────────────────────────────
    ax = axes[1, 2]
    sc = ax.scatter(cx, cy,
                    c=features["height_mean"],
                    s=0.3, alpha=0.5, cmap='RdYlGn')
    plt.colorbar(sc, ax=ax, label='mean height (m)')
    ax.set_xlabel("X (m)"); ax.set_ylabel("Y (m)")
    ax.set_title("Top-down: Mean Height")
    ax.set_aspect('equal')

    plt.tight_layout()
    plot_path = os.path.join(
        save_dir,
        f"{os.path.splitext(frame_name)[0]}_quality.png"
    )
    plt.savefig(plot_path, dpi=150, bbox_inches='tight')
    plt.show()
    print(f"Saved: {plot_path}")


# ─────────────────────────────────────────
# STORAGE VERIFICATION
# ─────────────────────────────────────────
def verify_storage(frame_id, save_dir, original_features):
    """
    Load saved voxels back and confirm they match original.
    """
    print(f"\n── Storage verification: {frame_id} ──")
    loaded = load_voxels(frame_id, save_dir)

    checks = [
        ("voxel count",
         len(loaded["unique_keys"]) == len(original_features["unique_keys"])),
        ("height_mean match",
         np.allclose(loaded["height_mean"],
                     original_features["height_mean"].astype(np.float32),
                     atol=1e-4)),
        ("height_min match",
         np.allclose(loaded["height_min"],
                     original_features["height_min"].astype(np.float32),
                     atol=1e-4)),
        ("point_count match",
         np.array_equal(loaded["point_count"],
                        original_features["point_count"])),
        ("levels match",
         np.array_equal(loaded["levels"],
                        original_features["levels"])),
    ]

    all_ok = True
    for name, result in checks:
        status = "✓" if result else "✗"
        print(f"  {status} {name}")
        if not result:
            all_ok = False

    # File size
    npz_path = os.path.join(save_dir, f"{frame_id}_voxels.npz")
    size_kb  = os.path.getsize(npz_path) / 1024
    print(f"  File size : {size_kb:.1f} KB")
    return all_ok


# ─────────────────────────────────────────
# MAIN
# ─────────────────────────────────────────
pipeline = VoxelPipeline(max_points=150000, max_voxels=100000)
_ = pipeline.process(load_points(FILES[0]))  # warmup

all_meta = []

for fpath in FILES:
    fname  = os.path.basename(fpath)
    fid    = os.path.splitext(fname)[0]

    print(f"\n{'='*60}")
    print(f"Processing {fname}")
    print(f"{'='*60}")

    # ── run pipeline ───────────────────────────────────
    points   = load_points(fpath)
    t0       = time.perf_counter()
    features = pipeline.process(points)
    elapsed  = (time.perf_counter() - t0) * 1000

    # ── save voxels ────────────────────────────────────
    out_path = save_voxels(features, fname, SAVE_DIR)
    print(f"Saved voxels → {out_path}")

    # ── quality report ─────────────────────────────────
    voxel_quality_report(features, points)
    check_zone_boundaries(features)

    # ── plots (first frame only to avoid too many images)
    if fid == "000000":
        voxel_quality_plots(features, fname, SAVE_DIR)

    # ── verify storage ─────────────────────────────────
    verify_storage(fid, SAVE_DIR, features)

    # ── collect metadata ───────────────────────────────
    pcount = features["point_count"]
    all_meta.append({
        "frame":         fid,
        "n_points":      int(len(points)),
        "n_voxels":      int(len(features["unique_keys"])),
        "n_l0":          int((features["levels"]==0).sum()),
        "n_l1":          int((features["levels"]==1).sum()),
        "n_l2":          int((features["levels"]==2).sum()),
        "pts_per_voxel": float(pcount.mean()),
        "height_range_mean": float(features["height_range"].mean()),
        "pipeline_ms":   float(elapsed),
        "fps":           float(1000/elapsed),
        "npz_size_kb":   float(
            os.path.getsize(
                os.path.join(SAVE_DIR, f"{fid}_voxels.npz")
            ) / 1024
        ),
    })

# ── save metadata ──────────────────────────────────────
meta_path = save_metadata(all_meta, SAVE_DIR)
print(f"\nMetadata saved → {meta_path}")

# ── final storage summary ──────────────────────────────
print("\n" + "="*70)
print("STORAGE SUMMARY")
print("="*70)
print(f"{'Frame':<12} {'Voxels':>8} {'pts/vox':>8} "
      f"{'FPS':>6} {'File KB':>8}")
print("-"*70)
for m in all_meta:
    print(f"{m['frame']:<12} {m['n_voxels']:>8,} "
          f"{m['pts_per_voxel']:>8.2f} "
          f"{m['fps']:>6.1f} "
          f"{m['npz_size_kb']:>8.1f}")

total_kb = sum(m['npz_size_kb'] for m in all_meta)
print(f"\n  Total storage (10 frames) : {total_kb:.1f} KB "
      f"= {total_kb/1024:.2f} MB")
print(f"  Avg per frame             : {total_kb/len(all_meta):.1f} KB")
print(f"\nFiles saved to: {SAVE_DIR}")
print("\nTo reload any frame later:")
print('  features = load_voxels("000000", SAVE_DIR)')

